// Generated by scripts/generate-data.mjs — do not hand-edit, regenerate instead.
import type {DateRow} from "./types";

export const TYNDALE_DATES: DateRow[] = [
  [
    "2026-08-21",
    "2026-08-21",
    "Fall registration deadline",
    "deadline"
  ],
  [
    "2026-08-27",
    "2026-08-27",
    "First day of modular classes",
    "term"
  ],
  [
    "2026-09-07",
    "2026-09-07",
    "Labour Day",
    "holiday"
  ],
  [
    "2026-09-07",
    "2026-09-09",
    "New student orientation",
    "term"
  ],
  [
    "2026-09-10",
    "2026-09-10",
    "Fall classes begin",
    "term"
  ],
  [
    "2026-09-15",
    "2026-09-15",
    "Commencement Chapel",
    "term"
  ],
  [
    "2026-09-23",
    "2026-09-23",
    "Last day to add/drop Fall courses without penalty",
    "deadline"
  ],
  [
    "2026-10-12",
    "2026-10-12",
    "Thanksgiving (no classes)",
    "holiday"
  ],
  [
    "2026-10-13",
    "2026-10-18",
    "Reading days (no classes)",
    "holiday"
  ],
  [
    "2026-11-02",
    "2026-11-02",
    "Fall graduation",
    "term"
  ],
  [
    "2026-11-18",
    "2026-11-18",
    "Final day to drop a Fall course",
    "deadline"
  ],
  [
    "2026-12-04",
    "2026-12-04",
    "Spring graduation early application deadline",
    "deadline"
  ],
  [
    "2026-12-09",
    "2026-12-09",
    "Last day of Fall classes",
    "term"
  ],
  [
    "2026-12-10",
    "2026-12-10",
    "Reading day (no classes)",
    "holiday"
  ],
  [
    "2026-12-11",
    "2026-12-11",
    "Winter registration deadline",
    "deadline"
  ],
  [
    "2026-12-11",
    "2026-12-18",
    "Fall final exams",
    "exam"
  ],
  [
    "2026-12-24",
    "2027-01-03",
    "Tyndale closed",
    "holiday"
  ],
  [
    "2027-01-04",
    "2027-01-08",
    "January intersession",
    "term"
  ],
  [
    "2027-01-07",
    "2027-01-07",
    "First day of modular classes",
    "term"
  ],
  [
    "2027-01-11",
    "2027-01-11",
    "Winter classes begin",
    "term"
  ],
  [
    "2027-01-22",
    "2027-01-22",
    "Last day to add/drop Winter courses without penalty",
    "deadline"
  ],
  [
    "2027-01-31",
    "2027-01-31",
    "Spring graduation final application deadline",
    "deadline"
  ],
  [
    "2027-02-15",
    "2027-02-15",
    "Family Day (no classes)",
    "holiday"
  ],
  [
    "2027-02-16",
    "2027-02-21",
    "Reading days (no classes)",
    "holiday"
  ],
  [
    "2027-03-19",
    "2027-03-19",
    "Final day to drop a Winter course",
    "deadline"
  ],
  [
    "2027-03-26",
    "2027-03-26",
    "Good Friday (no classes or exams)",
    "holiday"
  ],
  [
    "2027-04-06",
    "2027-04-06",
    "Convocation Chapel",
    "term"
  ],
  [
    "2027-04-12",
    "2027-04-12",
    "Last day of Winter classes",
    "term"
  ],
  [
    "2027-04-13",
    "2027-04-13",
    "Reading day (no classes)",
    "holiday"
  ],
  [
    "2027-04-14",
    "2027-04-22",
    "Winter final exams",
    "exam"
  ],
  [
    "2027-05-29",
    "2027-05-29",
    "Spring Convocation, Arts & Sciences",
    "term"
  ]
];
