// Generated by scripts/generate-data.mjs — do not hand-edit, regenerate instead.
import type {Minor} from "./types";

export const MINORS: Minor[] = [
  {
    "id": "m-bst",
    "name": "Biblical Studies and Theology",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-Biblical-Studies-and-Theology-2026-2027.pdf",
    "rows": [
      "BSTH 101",
      "BSTH 102",
      "BSTH 201",
      "BSTH 270",
      {
        "el": "Old Testament course (BSTH 310–329)",
        "cr": 3
      },
      {
        "el": "New Testament course (BSTH 330–349)",
        "cr": 3
      },
      {
        "el": "Christian Theology course (BSTH 360–379)",
        "cr": 3
      },
      {
        "el": "BSTH course",
        "cr": 3
      }
    ]
  },
  {
    "id": "m-bus",
    "name": "Business Administration",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-Business-2026-2027.pdf",
    "rows": [
      "BUSI 101",
      "BUSI 215",
      "BUSI 231",
      "BUSI 261",
      "BUSI 262",
      {
        "el": "BUSI 2000-level course",
        "cr": 3
      },
      {
        "el": "BUSI 3000-level courses",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-child",
    "name": "Children's Ministry",
    "total": 18,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-Childrens-Ministry-2026-2027.pdf",
    "rows": [
      "CHRI 121",
      "CHRI 322",
      "CHRI 329",
      "CHRI 344",
      {
        "el": "CHRI courses or PSYC 211",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-apol",
    "name": "Christian Apologetics",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-Christian-Apologetics-2026-2027.pdf",
    "rows": [
      "PHIL 171",
      "PHIL 201",
      "PHIL 261",
      "PHIL 294",
      {
        "pick": 1,
        "of": [
          "PHIL 321",
          "PHIL 322"
        ]
      },
      {
        "el": "Approved apologetics electives",
        "cr": 9
      }
    ],
    "note": "Not open to Philosophy majors."
  },
  {
    "id": "m-engl",
    "name": "English",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-English-2026-2027.pdf",
    "rows": [
      "ENGL 101",
      "ENGL 102",
      {
        "pick": 1,
        "of": [
          "ENGL 262",
          "ENGL 263"
        ]
      },
      {
        "el": "ENGL 3000-level courses",
        "cr": 6
      },
      {
        "el": "ENGL courses",
        "cr": 9
      }
    ]
  },
  {
    "id": "m-ethlaw",
    "name": "Ethics and Law",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-08/Tyndale-University-Program-Requirements-Ethics-and-Law-2026-2027.pdf",
    "rows": [
      "BUSI 321",
      "PHIL 201",
      "PHIL 243",
      "PHIL 311",
      "PHIL 328",
      "PHIL 370",
      {
        "pick": 2,
        "of": [
          "BSTH 321",
          "PHIL 213",
          "PHIL 215",
          "PHIL 313",
          "PHIL 330",
          "PHIL 481"
        ]
      }
    ],
    "note": "Not open to Philosophy majors."
  },
  {
    "id": "m-hgs",
    "name": "History and Global Studies",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-09/Tyndale-University-Program-Requirements-History-and-Global-Studies-2026-2027.pdf",
    "rows": [
      "HIST 101",
      "HIST 102",
      {
        "el": "HIST 2000-level courses",
        "cr": 15
      },
      "HIST 301"
    ]
  },
  {
    "id": "m-ics",
    "name": "Intercultural Studies",
    "total": 18,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-09/Tyndale-University-Program-Requirements-Intercultural-Studies-2026-2027.pdf",
    "rows": [
      "CHRI 121",
      "CHRI 344",
      "CHRI 361",
      "CHRI 369",
      {
        "el": "CHRI or IDVP courses",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-ling",
    "name": "Linguistics",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-09/Tyndale-University-Program-Requirements-Linguistics-2026-2027.pdf",
    "rows": [
      "LING 101",
      "LING 102",
      {
        "el": "LING 2000-level courses",
        "cr": 12
      },
      {
        "el": "LING 3000-level courses",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-meda",
    "name": "Media Arts",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-09/Tyndale-University-Program-Requirements-Media-Arts-Business-2026-2027.pdf",
    "rows": [
      {
        "pick": 1,
        "of": [
          "MEDA 111",
          "MEDA 113"
        ]
      },
      "MEDA 121",
      "MEDA 210",
      {
        "pick": 1,
        "of": [
          "MEDA 230",
          "PHIL 241"
        ]
      },
      "MEDA 212",
      {
        "el": "MEDA 3000-level courses",
        "cr": 9
      }
    ]
  },
  {
    "id": "m-mwa",
    "name": "Music and Worship Arts",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-09/Tyndale-University-Program-Requirements-Music-Worship-Arts-Minor-2026-2027.pdf",
    "rows": [
      "CHRI 346",
      "CHRI 347",
      "MUSC 101",
      "MUSC 202",
      "MUSC 369",
      {
        "pick": 1,
        "of": [
          "MUSC 1B1",
          "MUSC 1C1",
          "MUSC 1J1",
          "MUSC 1S1"
        ]
      },
      {
        "el": "Applied Music or music elective",
        "cr": 2
      },
      {
        "el": "MUSC, ARTM 310, ARTM 312 or CHRI 340",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-past",
    "name": "Pastoral Ministry",
    "total": 18,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-10/Tyndale-University-Program-Requirements-Pastoral-Ministry-2026-2027.pdf",
    "rows": [
      "CHRI 121",
      "CHRI 343",
      "CHRI 344",
      "CHRI 349",
      {
        "el": "CHRI course, PSYC 211 or PSYC 212",
        "cr": 6
      }
    ]
  },
  {
    "id": "m-phil",
    "name": "Philosophy",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-10/Tyndale-University-Program-Requirements-Philosophy-2026-2027.pdf",
    "rows": [
      "PHIL 171",
      "PHIL 201",
      "PHIL 370",
      {
        "el": "PHIL 2000-level courses",
        "cr": 6
      },
      {
        "el": "PHIL 3000-level courses",
        "cr": 9
      }
    ]
  },
  {
    "id": "m-psyc",
    "name": "Psychology",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-10/Tyndale-University-Program-Requirements-Psychology-with-DCP-2026-2027.pdf",
    "rows": [
      "PSYC 101",
      "PSYC 102",
      {
        "el": "PSYC 2000-level courses",
        "cr": 6
      },
      {
        "el": "PSYC 3000-level courses",
        "cr": 12
      }
    ]
  },
  {
    "id": "m-soci",
    "name": "Sociology",
    "total": 24,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-10/Tyndale-University-Program-Requirements-Sociology-2026-2027.pdf",
    "rows": [
      "SOCI 101",
      "SOCI 102",
      {
        "el": "SOCI 2000-level courses",
        "cr": 6
      },
      {
        "el": "SOCI 3000-level courses",
        "cr": 12
      }
    ]
  },
  {
    "id": "m-youth",
    "name": "Youth Ministry",
    "total": 18,
    "pdf": "https://www.tyndale.ca/sites/default/files/programs/2026-10/Tyndale-University-Program-Requirements-Youth-Ministry-2026-2027.pdf",
    "rows": [
      "CHRI 121",
      "CHRI 339",
      "CHRI 344",
      {
        "pick": 1,
        "of": [
          "CHRI 331",
          "CHRI 332"
        ]
      },
      {
        "el": "CHRI courses or PSYC 211",
        "cr": 6
      }
    ]
  }
];
