// Generated by scripts/generate-data.mjs — do not hand-edit, regenerate instead.
import type {Term} from "./types";

export const TERMS: Term[] = [
  {
    "id": "F26",
    "name": "Fall 2026",
    "start": "2026-09-10",
    "end": "2026-12-09"
  },
  {
    "id": "W27",
    "name": "Winter 2027",
    "start": "2027-01-11",
    "end": "2027-04-12"
  }
];
