// Regenerates src/data/2026-27/*.ts from reference/programs.js and reference/catalog.json.
// Run with: node scripts/generate-data.mjs
// For a future year, copy reference/programs.js + catalog.json into a dated reference set,
// update the paths below and the OUT_DIR, and re-run.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { Module } from "node:module";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "src/data/2026-27");

const programsSrc = readFileSync(path.join(ROOT, "reference/programs.js"), "utf8");
const wrapped =
  programsSrc +
  "\nmodule.exports = {PROGRAMS, MINORS, CONCENTRATIONS, CREDIT_OVERRIDES, TYNDALE_DATES, TERMS};\n";
const m = new Module(path.join(ROOT, "reference/programs.js"));
m.filename = path.join(ROOT, "reference/programs.js");
m._compile(wrapped, m.filename);
const { PROGRAMS, MINORS, CONCENTRATIONS, CREDIT_OVERRIDES, TYNDALE_DATES, TERMS } = m.exports;

const catalog = JSON.parse(readFileSync(path.join(ROOT, "reference/catalog.json"), "utf8"));
const descriptions = JSON.parse(readFileSync(path.join(ROOT, "reference/courseDescriptions.json"), "utf8"));
const courseDescriptions = Object.fromEntries(
  descriptions.map(({ code, description, prereq }) => [code, { description, prereq }]),
);

mkdirSync(OUT_DIR, { recursive: true });

function write(file, baseType, fullType, exportName, value) {
  const banner = "// Generated by scripts/generate-data.mjs — do not hand-edit, regenerate instead.\n";
  const content =
    banner +
    `import type {${baseType}} from "./types";\n\n` +
    `export const ${exportName}: ${fullType} = ${JSON.stringify(value, null, 2)};\n`;
  writeFileSync(path.join(OUT_DIR, file), content);
  console.log(`wrote ${file}`);
}

write("programs.ts", "Program", "Program[]", "PROGRAMS", PROGRAMS);
write("minors.ts", "Minor", "Minor[]", "MINORS", MINORS);
write("concentrations.ts", "Concentration", "Concentration[]", "CONCENTRATIONS", CONCENTRATIONS);
write("creditOverrides.ts", "CreditOverrides", "CreditOverrides", "CREDIT_OVERRIDES", CREDIT_OVERRIDES);
write("dates.ts", "DateRow", "DateRow[]", "TYNDALE_DATES", TYNDALE_DATES);
write("terms.ts", "Term", "Term[]", "TERMS", TERMS);
write("catalog.ts", "CatalogEntry", "CatalogEntry[]", "CATALOG", catalog);
write("courseDescriptions.ts", "CourseDescriptions", "CourseDescriptions", "COURSE_DESCRIPTIONS", courseDescriptions);

console.log("done.");
